### ISSUE TITLE
Uncaught (in promise) Bad Request /.atom/packages/better-git-blame/dist/bundle.js:17119

### ISSUE THREAD

**Issue by Gabb1995** [Stepsize/atom-better-git-blame#16]
Happens when I am hovering over a commit inside the view.
![peek 2017-10-05 17-58](https://user-images.githubusercontent.com/20728259/31237293-d081d4c2-a9f6-11e7-9bd5-26eb3335ff06.gif)

**Comment by pthm** [comment]
Hi @Gabb1995 thanks for the report.

Going to take a look at this now and try and figure out whats going wrong. If its an easy fix should be able to get a new version out today. I will update here when I've gathered some more info.

**Comment by pthm** [comment]
I've taken a look and made some changes to the code I believe to be causing the issue. However I have been unable to reproduce the error you are seeing.

If possible could you post the full stack-trace that is being logged to the console?

If not I can release an updated version and if the problem is solved we can close this Issue.

**Comment by Gabb1995** [comment]
So in the console it only shows this: `Uncaught (in promise) Bad Request` in `/home/gabriel/.atom/packages/better-git-blame/dist/bundle.js` when error happens but when I start atom I am getting these in the console as well maybe they are other issues or related.

`config --global user.email`

```
Uncaught (in promise) Error: Failed to fetch email or create fallback
    at /home/gabriel/.atom/packages/better-git-blame/dist/bundle.js:27762:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/gabriel/.atom/packages/better-git-blame/dist/bundle.js:17118:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Then when I open a file I get a bunch of these: 
`Uncaught (in promise) Bad Request`

**Comment by pthm** [comment]
Thanks for the extra info, Just released version v0.2.2 with the potential fix merged in.
Give it a whirl and let us know if you are still having problems.

**Comment by Gabb1995** [comment]
Unfortunately it is still happening, same error as in the gif. Let me know what other info I can provide.

**Comment by nomeyer** [comment]
Hey @Gabb1995, thanks again for checking in. @pthm is off for a few days so I'm taking a look at this.

If you have a 2-3 minutes, it'd be really helpful if you could do the following:
1. As a sanity check, take a look at the plugin in the settings and make sure no update is available, and install it if there is one.
2. Restart Atom, and before doing anything else open up the console (`cmd` + `alt` + `i` on mac). Let me know what's there please (the whole thing ideally).
3. Open a file. Lemme know if you see anything new in the console.
4. Toggle the blame gutter. Lemme know if you see anything new in the console.
5. Mouse over the gutter to show a popover. Lemme know if you see anything new in the console.
6. Repeat 5 on a different gutter item.

That should help me narrow things down. I'm expecting an error at step 2, but there should be some stuff preceding the error `Uncaught (in promise) Error: Failed to fetch email or create fallback`. Then I'd also expect an error at step 5, but not 6.

Finally, if you could let me know which OS you run, and whether you see any output to the command `git config --global user.email`(no need to give me the output itself), that would be super helpful.

Thanks a lot!

**Comment by Gabb1995** [comment]
Hi,
1. I am on version 0.2.2
2. This is the log of when I open atom. 
[atom-log.log](https://github.com/Stepsize/atom-better-git-blame/files/1370927/atom-log.log)
3. No logs happen.
4. ```/home/gabriel/.atom/packages/better-git-blame/dist/bundle.js:17119 Uncaught (in promise) Bad Request
rejected @ /home/gabriel/.atom/packages/better-git-blame/dist/bundle.js:17119
_tickCallback @ internal/process/next_tick.js:103
internal/process/next_tick.js:103 Uncaught (in promise) Bad Request
_tickCallback @ internal/process/next_tick.js:103
internal/process/next_tick.js:103 Uncaught (in promise) Bad Request
_tickCallback @ internal/process/next_tick.js:103
internal/process/next_tick.js:103 Uncaught (in promise) Bad Request
_tickCallback @ internal/process/next_tick.js:103
internal/process/next_tick.js:103 Uncaught (in promise) Bad Request```
5. `/home/gabriel/.atom/packages/better-git-blame/dist/bundle.js:17119 Uncaught (in promise) Bad Request
rejected @ /home/gabriel/.atom/packages/better-git-blame/dist/bundle.js:17119`
6. `/home/gabriel/.atom/packages/better-git-blame/dist/bundle.js:17119 Uncaught (in promise) Bad Request
rejected @ /home/gabriel/.atom/packages/better-git-blame/dist/bundle.js:17119`

I am running Ubuntu 17.04, the `git config --global user.email` command prints out the correct email.

**Comment by nomeyer** [comment]
Thanks a lot @Gabb1995 

I'm looking into this now but I wanted to let you know that I've edited your message to stop linking to your log file because a package you're using (`sync-settings`) logged a GitHub access token... You may want to revoke that token just to be safe.

**Comment by nomeyer** [comment]
Ok so we've deployed a fix to our integrations service (which serves up pull request & related issue data). This should fix the bad requests of step 4.

For those of 5 & 6, I'm not 100%. I think it might be the same issue but I can't be sure.

The next plugin release will include some handling of bad requests & further logs that should allow us to get to the bottom of this if it's not fully fixed yet.

**Comment by Gabb1995** [comment]
I am not getting the errors anymore with the latest update. Thanks.
