### ISSUE TITLE
Ability to copy commit hash to clipboard

### ISSUE THREAD

**Issue by eltian** [Stepsize/atom-better-git-blame#28]
I found this little feature quite useful on similar packages, and thought it wouldn't be too hard to add some simple functionality to allow copying the commit hast to the clipboard.

**Comment by nomeyer** [comment]
Hi @eltian, thanks for the suggestion!

Version 0.4.2 is now available and copies the commit hash to your clipboard when you click on the short commit hash in the tooltip.

(This previously opened the commit in your browser, which you can still do by clicking on the commit title in the tooltip.)

✌️

**Comment by nomeyer** [comment]
Just released a missing bit with 0.4.3 – a short-lived success notification when copying the hash.
