### ISSUE TITLE
Commit url is broken for ssh configured remote

### ISSUE THREAD

**Issue by opomuc** [Stepsize/atom-better-git-blame#29]
When clicking on the commit in blame interface it redirects to incorrect url:
```
https://gitlab.com/git/<repo_path>/commit/<commit_hash>
```
`git/` is not required here.

Git is configured to use ssh, such as `git@gitlab.com:<repo_path>.git`. Maybe that is what causes the issue.

**Comment by nomeyer** [comment]
Hi @opomuc, thanks for reporting this issue.

I've managed to reproduce it. It seems to be an issue with the library we're using for Git URL parsing. I've raised it here https://github.com/IonicaBizau/git-url-parse/issues/63.

I'll release a temporary fix shortly.

**Comment by nomeyer** [comment]
@opomuc if you update to version 0.4.2 your commit URLs should be correct 👍

**Comment by opomuc** [comment]
It works. Thanks for the quick fix!
