### ISSUE TITLE
Feature: inline blame

### ISSUE THREAD

**Issue by bennypowers** [Stepsize/atom-better-git-blame#42]
This plugin is awesome thank you for publishing it.

Please consider adding an inline git blame option (a la [atom-inine-blame](https://atom.io/packages/atom-inline-blame)), which would replace the gutter.

**Comment by nomeyer** [comment]
Hi @bennypowers, glad you're enjoying using this plugin and thank you for the suggestion 🙂

Unfortunately we're no longer building new features for this plugin, sorry. If we get back to it we'll certainly consider adding an inline option though.

✌️
