### ISSUE TITLE
Question: Can I see the history?

### ISSUE THREAD

**Issue by asdf23** [Stepsize/atom-better-git-blame#46]
Is it possible to see what the code was.. given a specific line of code, I want to know what it was before the current line that I am seeing. Does this tool do that?

**Comment by nomeyer** [comment]
Hi @asdf23 – the way to do this would be to click on the blame commit to open it up in your browser and view the state of the code before that commit.

I appreciate there could be a better way to do it, but this plugin is not under active development currently, so hope this helps anyway!

**Comment by asdf23** [comment]
Thanks, it'd be a nice feature though
